### ISSUE TITLE
using maximum_messages parameter on listen message seems to throw error

### ISSUE THREAD

**Issue by jpgreenall** [dowjones/dj-dna-streams-python#15]
On the final iteration of the main loop in the listen method, then batch_size value gets set to zero which then causes error to be thrown by pull.

if condition on the loop is < instead of <= this seems to fix it.

**Comment by zakagan** [comment]
Yes, that seems to be the fix. Thanks for catching this issue

**Comment by jpgreenall** [comment]
@zakagan thanks for confirming. is this repo still under active dev? Any scheduled date for next release?
Best,
John

**Comment by zakagan** [comment]
@jpgreenall it is. We've pushed a small update with the fix. It is tagged in a new release, release-1.3.2
