### ISSUE TITLE
Restricting google-cloud-pubsub version

### ISSUE THREAD

**Issue by jkhalsa-arabesque** [dowjones/dj-dna-streams-python#24]
https://github.com/dowjones/dj-dna-streams-python/blob/2c513189e001dc4e14253b2ab805d41bb74bb5cd/setup.py#L21-L28

This package breaks when trying to listen with newer versions of google-cloud-pubsub. By restricting the max version here, it would prevent issues when pip installing via the github link.

**Comment by zakagan** [comment]
I see the line is between 1.7.0 and 2.0.0 for the pubsub client. I've made this requirement more strict as to require 1.7.0, and in the future we may update this to allow the most up to date client library
